Deprecation: #96641 - Link-related functionality in ContentObjectRend…
TYPO3-Documentation/TYPO3CMS-Reference-Typoscript pull request #523
Opened 2022-04-30 22:00 UTC by linawolf

…erer

solves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/58

2022-04-30 22:01 UTC, linawolf commented
We can backport this change as typolink() was already recommended to be used in 11.5

2022-06-10 13:51 UTC, brotkrueml requested changes

2022-06-10 13:51 UTC, brotkrueml commented on Documentation/Functions/Stdwrap.rst
> +            $content = $this->cObj->typoLink($content, $conf['typolink']);
```suggestion
            $content = $this->cObj->typoLink($content, ['parameter' => $conf['typolink']]);
```

2022-06-11 09:00 UTC, brotkrueml approved these changes

2022-06-11 16:02 UTC, merged