Add warning for using the DatabaseQueryProcessor
TYPO3-Documentation/TYPO3CMS-Reference-Typoscript pull request #568
Opened 2022-08-05 18:52 UTC by typecat

The DatabaseQueryProcessor currently has issues with language/ version overlays, that cannot be easily resolved (complexity: nightmare). Thus, bugs like https://forge.typo3.org/issues/85284 or https://forge.typo3.org/issues/88071 occur.

See https://forge.typo3.org/issues/85284#note-5 for a more detailed explanation.

2022-08-05 18:57 UTC, linawolf approved these changes

2022-08-05 18:58 UTC, brotkrueml requested changes

2022-08-05 18:58 UTC, brotkrueml commented on Documentation/ContentObjects/Fluidtemplate/DataProcessing/DatabaseQueryProcessor.rst
> +.. warning:: Be careful when the DatabaseQueryProcessor, as you may run
```suggestion
.. warning:: Be careful when using the DatabaseQueryProcessor, as you may run
```

2022-08-05 18:59 UTC, brotkrueml approved these changes

2022-08-05 19:19 UTC, merged

2022-08-07 09:15 UTC, linawolf commented
@typecat the file didn't exist in 10.4 yet, so please make a manual backport if needed

2022-08-08 15:25 UTC, lolli42 commented
post +1.
Thanks for this warning.

2022-09-06 08:42 UTC, linawolf commented
@typecat the page did not exist in v10 yet. Please make a separate PR for v10 if needed

2022-09-09 14:46 UTC, typecat commented
Ah, thanks for the hint. I'll see if I find it in the docs for v10.