[TASK] Overhaul typolink chapter
TYPO3-Documentation/TYPO3CMS-Reference-Typoscript pull request #675
Opened 2022-12-12 15:37 UTC by linawolf

Introduce custom confval directive for typolink

references #658
releases: main, 11.5

2022-12-12 17:09 UTC, brotkrueml requested changes

2022-12-15 18:04 UTC, linawolf commented on Documentation/Functions/Typolink.rst
> +..  attention::
No me neither. Shall we drop this?

2022-12-17 17:16 UTC, brotkrueml approved these changes

2022-12-17 17:16 UTC, brotkrueml commented on Documentation/Functions/Typolink.rst
> +..  attention::
Asked in the typoscript Slack channel. Let's leave it in for now.

2022-12-17 19:42 UTC, merged