Move example with typeNum
TYPO3-Documentation/TYPO3CMS-Reference-Typoscript pull request #730
Opened 2023-04-14 13:14 UTC by sfroemkenjw

Hello,

with following change:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100405-PropertyTypoScriptFrontendController-type.html

you can not access $TSFE->type anymore. That's why I have moved the example to the new request.getPageAttributes() location.

But be careful:
Doing so, will result in an Exception while opening the ExtensionManager. I already have added a forge ticket: https://forge.typo3.org/issues/100595

Stefan

2023-04-14 14:33 UTC, brotkrueml commented
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/444

2023-04-14 14:35 UTC, brotkrueml commented
@sfroemkenjw Thank you for the PR. I suggest to wait with the merge until the mentioned forge issue is resolved.

2023-04-14 16:32 UTC, brotkrueml requested changes
The issue in backend seems to be fixed in main branch (according to Oli and also I cannot reproduce it anymore).

But: The section you adjusted is about `getTSFE()`. Therefore, I suggest to remove the `getTSFE().type`  example there. Additionally, add the typenum snippet in the `request.getPageArguments()` section as example:
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Conditions/Index.html#request-getpagearguments

2023-04-17 05:29 UTC, sfroemkenjw commented
Please have a look into my change. It exactly does what you describe ;-)

2023-04-17 05:31 UTC, brotkrueml approved these changes

2023-04-17 05:32 UTC, merged